version: '3'
services:
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    container_name: share_tech_front
    depends_on: 
      - api
    environment: 
      API_HOST: api
      API_PORT: 3000
    ports:
      - 8080:3000
    tty: true
    stdin_open: true
    volumes:
      - ./front/:/myapp