version: '3'
services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    container_name: share_tech_api
    command: python django_api/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    tty: true
    stdin_open: true
    volumes:
      - ./api/:/src/app
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    container_name: statech_front
    environment: 
      API_HOST: api
      API_PORT: 5000
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    volumes:
      - ./front/:/myapp